# Generated by Django 4.2.5 on 2024-08-23 04:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("userauths", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customuser",
            name="full_name",
        ),
    ]
